// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RedlockDeneme.Data.Context;

#nullable disable

namespace RedlockDeneme.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20250605095026_YeniDegisiklikler")]
    partial class YeniDegisiklikler
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RedlockDeneme.Data.Entity.Sepet", b =>
                {
                    b.Property<int>("SepetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SepetId"));

                    b.Property<int>("Adet")
                        .HasColumnType("int");

                    b.Property<string>("UrunAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UrunId")
                        .HasColumnType("int");

                    b.HasKey("SepetId");

                    b.HasIndex("UrunId");

                    b.ToTable("Sepets");
                });

            modelBuilder.Entity("RedlockDeneme.Data.Entity.Stok", b =>
                {
                    b.Property<int>("StokId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StokId"));

                    b.Property<string>("StokAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StokSayisi")
                        .HasColumnType("int");

                    b.HasKey("StokId");

                    b.ToTable("Stoks");
                });

            modelBuilder.Entity("RedlockDeneme.Data.Entity.Sepet", b =>
                {
                    b.HasOne("RedlockDeneme.Data.Entity.Stok", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Urun");
                });
#pragma warning restore 612, 618
        }
    }
}
